"""empty message

Revision ID: 5ead40813961
Revises: 8b4d7f9e1fe2
Create Date: 2024-11-29 22:45:49.876086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ead40813961'
down_revision = '8b4d7f9e1fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('piercings', schema=None) as batch_op:
        batch_op.alter_column('artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piercings', schema=None) as batch_op:
        batch_op.alter_column('artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('global_settings')
    # ### end Alembic commands ###
