"""empty message

Revision ID: 8b4d7f9e1fe2
Revises: 198e1023d577
Create Date: 2024-11-26 14:44:47.212787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b4d7f9e1fe2'
down_revision = '198e1023d577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piercings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.DateTime(), nullable=False),
    sa.Column('appointment_date', sa.DateTime(), nullable=False),
    sa.Column('piercing_type', sa.String(length=50), nullable=False),
    sa.Column('jewelry_type', sa.String(length=50), nullable=False),
    sa.Column('placement', sa.String(length=50), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('studio_location', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('call_or_text_preference', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name='fk_piercing_artist'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('piercings')
    # ### end Alembic commands ###
